// Generated by CoffeeScript 1.9.3
var express, router;

express = require('express');

router = express.Router();

router.get('/', function(req, res, next) {
  return res.render('index', {
    title: 'Express'
  });
});

router.get('/json', function(req, res) {
  var sampleObject;
  sampleObject = {
    "name": "P",
    3: true
  };
  return res.jsonp(sampleObject);
});

router.get('/hit', function(req, res) {
  var db, loadHIT, mongoose, opts;
  mongoose = require('mongoose');
  mongoose.connect('mongodb://localhost/test');
  db = mongoose.connection;
  loadHIT = require('../loadHIT');
  opts = {
    user: "TEST",
    taskset_id: "TEST",
    hit_id: "557df4899b962f181de3da0c",
    lock: true,
    itemProjection: {
      url: 1,
      description: 1,
      title: 1,
      image: 1,
      likes: 1,
      repins: 1
    }
  };
  db.on('error', console.error.bind(console, 'connection error:'));
  return db.once('open', function() {
    return loadHIT(opts, function(err, results) {
      res.jsonp(results);
      return mongoose.disconnect();
    });
  });
});

module.exports = router;
